[tool.poetry]
name = "poc-scraping"
version = "0.1.0"
description = "Scraping with gazpacho"
authors = ["Fabricio Nogueira <nogsantos@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
gazpacho = "^1.1"
pandas = "^1.3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
